Lesson3 main page of the theatre
AleksandrCherniavskiy/Github-Frontend-JS-2018-2019 pull request #3
Opened 2018-11-04 22:09 UTC by AleksandrCherniavskiy

2018-11-04 22:12 UTC, AleksandrCherniavskiy commented
![hw3](https://user-images.githubusercontent.com/43580496/47970526-6852c480-e08f-11e8-82cd-a1aa5c28e85a.png)

2018-11-06 21:24 UTC, yana-tsylinska requested changes

2018-11-06 21:24 UTC, yana-tsylinska commented on HW3/index.html
> +        <a name="top"></a>
посилання всередині селекта? точно гарна ідея?
+ в HTML5 для якоря треба просто id використовувати

2018-11-06 21:24 UTC, yana-tsylinska commented on HW3/index.html
> +        <li><img src="img/icon-photo.png" alt="фото"><a href="#">Фотоархів</a></li>
в даному випадку це просто іконки, тому alt тут скоріш за все не потрібен, а от width/height можна було б додати)

2018-11-06 21:24 UTC, yana-tsylinska commented on HW3/index.html
> +    <div class="horizontal-line"></div>
окремий елемент для чисто візуального оформлення - погана практика, краще навішати стилі на ::before)

2018-11-08 21:39 UTC, merged